- "name": "Affects: Documentation :memo:"
  "from_name": "docs"
  "color": "6EE07E"
- "name": "Affects: Config :wrench:"
  "color": "F5C53A"
- "name": "Affects: Code :scroll:"
  "color": "F5C53A"

- "name": "Priority: High"
  "from_name": "Priority1"
  "color": "d93f0b"
- "name": "Priority: Normal"
  "from_name": "Priority2"
  "color": "fbca04"
- "name": "Priority: Low"
  "from_name": "Priority3"
  "color": "c2e0c6"

- "name": "Type: Bug :bug:"
  "from_name": "bug"
  "color": "b60205"
- "name": "Type: Enhancement :sparkles:"
  "from_name": "enhancement"
  "color": "c5def5"
- "name": "Type: Question :question:"
  "from_name": "question"
  "color": "d4c5f9"
- "name": "Type: Duplicate :gemini:"
  "from_name": "duplicate"
  "color": "cfd3d7"
- "name": "Type: Good first issue :beginner:"
  "from_name": "good first issue"
  "color": "a8e38f"
- "name": "Type: Help wanded"
  "from_name": "help wanted"
  "color": "00a38b"
- "name": "Type: Invalid :no_entry_sign:"
  "from_name": "invalid"
  "color": "e3e3e3"
  "description": "Does not follow template or other formal guideline"
- "name": "Type: Wont fix :no_entry_sign:"
  "from_name": "wontfix"
  "color": "e3e3e3"
  "description": "Works as intended, out of scope or similar"

